# Generated by Django 3.2.4 on 2021-08-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user', '0002_auto_20210818_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
