# Generated by Django 3.2.4 on 2021-08-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
